---
title: "Day 2 R"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

we are going to work on adult dataset. lets apply some pre processing tasks on adult dataset

Lets start out first r-chunk
```{r}
#set the working directory
setwd("C:/Users/Nathan/Desktop/DS110")

#lets see whether we set the working directory to the correct location, by displaying whats in the current directory
dir()

#lets read the dataset
#we know the dataset has column labels and the data are separated by "tabs"
AdultData=read.table("AdultData1000.txt", sep ="\t", header=TRUE)

#Display the top 6 records of the dataset
head(AdultData)

#Dimension of the dataset. ie #rows and columns
dim(AdultData)

#attach the dataset so we can access the variables directly by their name. otherwise we will have to call datasetname$variablename
attach(AdultData)

#Let's output the age variable
age

#Let's see the summary of all variables in the dataset
summary(AdultData)

#Let's see the structure of the dataset: how the dataset has recognized their variables
str(AdultData)

#when you read the table it reads the dataset as a matrix with columns and rows. so we can access each "cell" with its row and column numbers
#lets display the value on 2nd row 3rd column
print("display the value on 2nd row 3rd column")
AdultData[2, 3]

print("display the 2rd row")
AdultData[2, ]

print("display the 3rd column")
AdultData[, 3]

#number of rows in a dataset
nrow(AdultData)

#number of column in a dataset
ncol(AdultData)

#Let's look at some of the variables that have been recognized as "char" variables; I want to know what type of values those variables hold
summary(workclass)
head(AdultData)

#Let's tell R about the factor variables we have. we are going to ID the factor variables by ourselves
AdultData$workclass=as.factor(AdultData$workclass)
AdultData$maritalStatus=as.factor(AdultData$maritalStatus)
AdultData$race=as.factor(AdultData$race)
AdultData$education=as.factor(AdultData$education)
AdultData$occupation=as.factor(AdultData$occupation)
summary(AdultData)
  
#Let's look at some of numerical descriptive statistics -- ie how to summarize quantitative variables
#Let's use age variable
mean(age)
#standard deviation
sd(age)

#variance
var(age)
sd(age)^2

summary(age)

#Lets do some graphical stats for quant variables
#we can make boxplot, histogram, normal probability plot

#histogram can be used to ID shape of distribtuion of a variable
hist(age)
hist(age, xlab="Age in years", ylab="*FREQ*", main="Here is the title")


#here is another plot that are commonly used to check the normality of a numerical / quant variable -- it is "Normal Probability Plot" 
qqnorm(age)

#NPP is used to check the normality of a variable. if the plot looks approximately linear, then we say the variable is approximately normally distributed, Above plot shows linear pattern so we can say age is normally distributed.

#usually histogram is used to check normality of a variable with larger num of datapoints and NPP is used for variables with fewer.

#boxplot is another important plot that helps us to check both normality and also outliers in a dataset.pch sets outlier to black circle, horiz changes to horiz.
boxplot(age, pch=16, horizontal = TRUE)

#note about data: based on boxplot, we can see there is one outlier and the age distribution is right skewed, which we could verify with a histogram as well


#____________________________________________
#summary statistics for Qualitative Variables
#____________________________________________
#what are our qualitative variables
str(AdultData)

attach(AdultData)
str(AdultData)

#For factor variables we can create Frequency tables

TblSex=table(sex)
TblSex

TblRace=table(race)
TblRace

#Create pie charts
pie(TblSex)
pie(TblRace)

#barcharts -- the function is called barplot()
barplot(TblSex)
barplot(TblRace)

```


# Outlier Analysis

```{r}
# we are doing outlier analysis in this r-chunk
head(AdultData)
str(AdultData)

# lets display column names
colnames(AdultData)

#lets create boxplot with the variables 1, 5, 13
boxplot(AdultData[ ,c(1,5,13)])

#Lets check hourperweek
boxplot(hoursPerWeek, horizontal = TRUE, pch=16)

#this is how we find the outlier values
OutlierValues=boxplot(hoursPerWeek, horizontal = TRUE, pch=16)$out
OutlierValues

#which record number contraint those outlier values
OutlierRows=which(hoursPerWeek==OutlierValues)
OutlierRows

length(OutlierRows)

#last step remove those rows from the dataset
NewAdultData=AdultData[-OutlierRows , ]

dim(NewAdultData)


```

Today we are learning a few more data preprocessing tasks using R

```{r}
head(AdultData)

#select a specific variable into a different variable
NewWorkClass=AdultData$workclass

NewWorkClass=AdultData[, 2]

#drop a variable and create a new dataset
NewwithoutWorkClass
head(NewwithoutworkClass)

#lets extract records those belonging to relationship="Own-child"
#here we are subsetting horizontally
Adultwithkids=subset(AdultData, relationship=="Own-child")
dim(Adultwithkids)
head(Adultwithkids)

#lets learn to extract a random sample of numbers from a given range, without replacement
RandomNotReplaced=sample(1:100, 80, replace=FALSE)
RandomNotReplaced

#Now roll a die 50 times (you may expect 1-6 several times throughout)
RollDie50=sample(1:6, 50,replace = TRUE)
RollDie50

#now we are going to divide the AdultDataset randomly so that 80% goes to train dataset and remaining 20% goes to test dataset.
#first extract 80% of row numbers randomly, then extract those 80% into the train dataset.
#now remove the 80% records from AdultDataSet to form Test dataset

#we know there are 1000 rows in AdultDataset
#we need 800 to Train and 200 to Test dataset

#Let's extract 800 random number without replacement from the 1 to 1000.
RandomRows=sample(1:1000, 800, replace=FALSE)

#lets make the Train dataset by extracting those rows from the Adultdataset
Train=AdultData[RandomRows , ]

#Now remove those 800 from AdultDataset to generate Test dataset
Test=AdultData[ -RandomRows, ]

dim(Train)
dim(Test)

#Let's write Train and Test dataset into files writ.table() function
write.table(Train, "AdultTrain.txt", sep="/t", row.names = FALSE)
write.table(Test, "AdultTest.txt", sep="/t", row.names = FALSE)
head(AdultData)

AdultData$relationship=as.factor(AdultData$relationship)

attach(AdultData)

#first lets see the values in the relationship variable
levels(relationship)

#lets first relabel the existing value to 1-5

NewRelationship=factor(relationship, level=c("Husband","Not-in-family","Other-relative","Own-child" , "unmarried", "Wife"), label=c("1", "2", "3", "4", "5",)

NewRelationshop[1,10]


#We assign numbers into NewRelationshop variable, Let's check whether it's a numerical variable
is.numeric(NewRelationshop)

#looks like it is not numeric even though it has numbers, so let's force it to be a numeric variable
NewRelationship2=as.numeric(NewRelationshop)

is.numeric(NewRelationship2)


```


```

